"""PBP -> drive-level table (§6a), plus the empirical starting-field-position
distributions the simulator samples from (§6b).

Defensive/return touchdowns and safeties are deliberately *not* folded into the drive
outcome classes. They are rare, and the points belong to the other team; modelling them
inside the multinomial makes it unstable. They are separate Poisson processes in
simulate.py.
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

import numpy as np
import pandas as pd

from ._shared import sim_core
from .config import CACHE_DIR,build_cache_signature,frame_signature,read_cached_frame,write_cached_frame

# Class labels and the field-position machinery are shared with ncaa-model; only the
# pbp -> drive-table builder below is NFL-specific.
TD, FG, NO_SCORE, TURNOVER = "TD", "FG", "NO_SCORE", "TURNOVER"
DRIVE_CLASSES = sim_core.DRIVE_CLASSES
DRIVE_CLASS_INDEX = sim_core.DRIVE_CLASS_INDEX
StartFieldPosition = sim_core.StartFieldPosition
fit_start_field_position = sim_core.fit_start_field_position

# The drive table's schema, in one place so the builder and the cache guard cannot drift
# apart. Adding a column here is what invalidates an old cache on disk.
DRIVE_COLUMNS = [
    "game_id", "season", "week", "season_type", "offense", "defense", "drive_number",
    "start_yardline_100", "n_plays", "result", "points_scored_on_drive",
    "is_home_offense", "prev_drive_turnover", "start_score_diff", "start_qtr",
    "start_gsr",
]

# fixed_drive_result -> our four classes.
#   "Opp touchdown" is a pick-six or fumble-six: from the offense's side the drive ended
#   in a turnover, and the resulting 7 points are generated by defensive_td_lambda.
#   "Safety" is likewise scored outside the multinomial via safety_lambda, so the drive
#   itself is NO_SCORE for the offense.
_RESULT_MAP = {
    "Touchdown": TD,
    "Field goal": FG,
    "Punt": NO_SCORE,
    "Turnover on downs": NO_SCORE,
    "Missed field goal": NO_SCORE,
    "End of half": NO_SCORE,
    "End of game": NO_SCORE,
    "Safety": NO_SCORE,
    "Turnover": TURNOVER,
    "Opp touchdown": TURNOVER,
}


def build_drive_table(
    pbp: pd.DataFrame,
    cache_key: "str | None" = None,
    refresh: bool = False,
) -> pd.DataFrame:
    """One row per drive.

    `start_yardline_100` is yards to the opponent's end zone at the drive's first
    scrimmage play, taken from the play-by-play rather than the `drive_start_yard_line`
    string so it is already numeric and already normalized.
    """
    path = CACHE_DIR / f"drives_{cache_key}.parquet" if cache_key else None
    signature=build_cache_signature(builder=Path(__file__),config={"drive_columns":DRIVE_COLUMNS},inputs=frame_signature(pbp,["game_id","fixed_drive","fixed_drive_result","posteam","defteam","yardline_100","game_seconds_remaining","special","play_type","score_differential","qtr","season","week","season_type","home_team","touchdown","td_team","extra_point_result","two_point_conv_result","field_goal_result"]),artifact_version=2)
    if path is not None and not refresh:
        cached = read_cached_frame(path, DRIVE_COLUMNS,signature)
        if cached is not None:
            return cached

    df = pbp[pbp["fixed_drive"].notna() & pbp["posteam"].notna()].copy()
    df = df.sort_values(
        ["game_id", "fixed_drive", "game_seconds_remaining"],
        ascending=[True, True, False],
    )

    # Special teams must be excluded before anything is read off "the first play of the
    # drive". nflverse attaches the kickoff to the receiving team's drive, so the first
    # row of a drive is typically a kickoff at yardline_100 == 35 -- taking field position
    # from it puts the average drive start near midfield instead of a team's own 27, which
    # inflates every scoring rate and flattens the key-number spikes the whole model
    # exists to reproduce.
    scrimmage = df[
        (df["special"] == 0) & df["play_type"].notna() & (df["play_type"] != "no_play")
    ]
    first_play = scrimmage.groupby(["game_id", "fixed_drive"], as_index=False).agg(
        start_yardline_100=("yardline_100", "first"),
        offense=("posteam", "first"),
        defense=("defteam", "first"),
        n_plays=("play_type", "size"),
        # Score state at the snap, from the offense's perspective. Needed for the
        # endgame layer: late-game drive outcomes depend far more on the scoreboard
        # than on team strength (a team trailing by 4-8 kicks a field goal on 0.3% of
        # late drives, against a 15.9% baseline).
        start_score_diff=("score_differential", "first"),
        start_qtr=("qtr", "first"),
        start_gsr=("game_seconds_remaining", "first"),
    )

    # Drive-level constants, safe to read from any row of the drive.
    grouped = df.groupby(["game_id", "fixed_drive"], as_index=False).agg(
        season=("season", "first"),
        week=("week", "first"),
        season_type=("season_type", "first"),
        home_team=("home_team", "first"),
        raw_result=("fixed_drive_result", "first"),
    )
    drives = grouped.merge(first_play, on=["game_id", "fixed_drive"], how="left")

    drives["result"] = drives["raw_result"].map(_RESULT_MAP)
    unmapped = drives.loc[
        drives["result"].isna() & drives["raw_result"].notna(), "raw_result"
    ].unique()
    if len(unmapped):
        raise ValueError(
            f"drives.build_drive_table: unmapped fixed_drive_result values {list(unmapped)}. "
            "Add them to _RESULT_MAP rather than letting them fall through to NO_SCORE."
        )
    drives = drives[drives["result"].notna()].copy()

    drives["points_scored_on_drive"] = _drive_points(pbp, drives)
    drives["is_home_offense"] = (drives["offense"] == drives["home_team"]).astype(int)
    drives = drives.rename(columns={"fixed_drive": "drive_number"})

    # Whether the *previous* drive in the same game ended in a turnover -- the only
    # condition the starting-field-position distribution is cut on.
    drives = drives.sort_values(["game_id", "drive_number"])
    prev = drives.groupby("game_id")["result"].shift(1)
    drives["prev_drive_turnover"] = (prev == TURNOVER).fillna(False)

    # A handful of possessions per season contain no scrimmage play at all -- a kickoff
    # returned for a touchdown, or a half expiring on the return. They have no starting
    # field position, they are not something the drive multinomial models, and the points
    # from them are already generated by the special-teams Poisson process.
    drives = drives[drives["start_yardline_100"].notna()].copy()
    drives["start_yardline_100"] = drives["start_yardline_100"].clip(1, 99)
    drives = drives[DRIVE_COLUMNS].reset_index(drop=True)
    if path is not None:
        write_cached_frame(drives,path,signature)
    return drives


def _drive_points(pbp: pd.DataFrame, drives: pd.DataFrame) -> np.ndarray:
    """Points the offense actually put on the board on each drive.

    Used for validation and for the observed points-per-drive column in the ratings
    sheet; the simulator draws its own conversions rather than reusing these.
    """
    df = pbp[pbp["fixed_drive"].notna() & pbp["posteam"].notna()]
    off_td = ((df["touchdown"] == 1) & (df["td_team"] == df["posteam"])).astype(float) * 6.0
    xp = (df["extra_point_result"] == "good").astype(float) * 1.0
    two = (df["two_point_conv_result"] == "success").astype(float) * 2.0
    fg = (df["field_goal_result"] == "made").astype(float) * 3.0
    pts = (off_td + xp + two + fg).groupby([df["game_id"], df["fixed_drive"]]).sum()
    idx = pd.MultiIndex.from_frame(drives[["game_id", "fixed_drive"]])
    return pts.reindex(idx).fillna(0.0).to_numpy()
